### ISSUE TITLE
Brainstorming: interesting AMR-tailored graph transformations

### ISSUE THREAD

**Issue by flipz357** [flipz357/smatchpp#11]
I think it would be interesting to have the option for some additional *useful but **optional** AMR graph transformations*:

They could make sense for some application or parsing diagnostics. 

To start with some examples:

---

**Sense2Node**

E.g.,

```
(j / jump-01
      :arg0 (f / frog))
```

would map to 

```
(j / jump
      :sense 01
      :arg0 (f / frog))
```

This transformation may be useful for some applications (and something like this could also give us a balanced mix of the concept-as-root and anonymous root issue @goodmami @jheinecke)

---

**AbstractifyNode**

E.g.,

```
(c / city
      :name (n / name
             :op1 "Berlin"))
```

would map to

```
(l / location
      :name (n / name
             :op1 "Berlin"))
```

This transformation may be useful for an additional informative parsing evaluation score. We could use the concept groups that I started building [here](https://github.com/flipz357/smatchpp/blob/main/smatchpp/resource/concept_groups.json)

---

And so on...

**Comment by flipz357** [comment]
**CollapseNamedEntity**

Smatch can be too biased towards NER, since it triggers larger structures that are easy to parse. This could inflate the score and distract from other semantic aspects. A NE-collapse could look like follows.

Given:

```
(p / university
      :name (n / name
           :op1 "university"
           :op2 "of" 
           :op3 "Heidelberg"))
```

There's reduction option 1 (very harsh):

```
(p / university
      :name "university of heidelberg"))
```

Reduction option 2 (less harsh):

```
(p / university
      :name-part-1 "university"
      :name-part-2 "of" 
      :name-part-3 "heidelberg"))
```

Both option would reduce possible score inflation of Smatch due to NEs and therefore something like this can be valuable as additional parsing diagnostics.

**Comment by jheinecke** [comment]
I think that goes slightly beyond graph comparison. I know that `a :relation b` and `b :relation-of a` are equivalent and smatch should not penalize upon that (as it does when comparing reified and un reified relations). But for this is a kind of normalisation done before evaluation. Smatch (and Smatch++) can therefore compare any graph (in PENMAN format) not just AMR-graphs if we keep any semantics ou of the "simple" graph ciomparison

**Comment by flipz357** [comment]
The aim would be to keep the generality of graph matching, but also allow some easy extension for AMR specific graph comparison.

Actually, I think this is already done by SMATCH++ slightly better than Smatch. For instance, while you are right that the `-of` inversion is a general "graph thing", Smatch does also manipulates `domain and mod`, which is bad when it comes to general graph. SMATCH++ instead relegates the AMR specific things to particular AMR-processing objects/modules such as `AMRStandardizer`. 

So there shouldn't be any barrier in SMATCH++ to keep being fully capable of matching any graph, but also performing stuff tailored to AMR, if we're wanting to do specific things with AMR. SMATCH++ can keep these two things separate (i.e., separate specific semantics from general graph matching).

PS @jheinecke To get a quick hunch for how the two things are kept separate within SMATCH++, see some examples in the [README](https://github.com/flipz357/smatchpp), particularly [Example II](https://github.com/flipz357/smatchpp#example-ii-smatch-matching-same-as-default-but-with-ilp), and [Example III](https://github.com/flipz357/smatchpp#example-iii-best-practice-matching-for-a-pair-of-amr-graphs). The modularity of SMATCH++ allows us to view Smatch as a pipeline, and load anything that we'd like. In the first eqxmple, we match two graphs without doing any manipulation, in the second, we match two graphs but perform default AMR standardization.

**Comment by flipz357** [comment]
Guess this issue can be closed, since maybe it's not the most pressing and [Example IX](https://github.com/flipz357/smatchpp#example-ix-plug-in-custom-standardizer-in-the-matching) now shows how to plug some custom graph transform in the pipeline.

**Comment by goodmami** [comment]
Sorry to comment on a closed issue (again), but I just want to add that I'd be very happy to see AMR-specific normalizations/transformations be done optionally. I [unsuccessfully](https://github.com/snowblink14/smatch/issues/10) tried to get Smatch to leave out the `:domain`/`:mod` normalization or put it behind an option because the basic algorithm was generally useful for graph comparison (and I was using it for DMRS comparison, specifically). That said, the sense2node and other transformations look interesting.

**Comment by flipz357** [comment]
Very generic transform, possible for all edge labeled graphs:

**Edge2Node** (sometimes also called Levi Graph):

```
(j / jump-01
      :arg0 (f / frog)
                 :mod (g / green)))
```
maps to

```
(j / jump-01
      :rel (a / arg0
             :rel (f / frog
                    :rel (m / mod
                           :rel (g / green)))))
```

The new graph doesn't have edge labels but is equivalent to the old graph.

**Comment by flipz357** [comment]
Edge2Node also puts spotlight on another interesting question: how much partial credit should be assigned to smaller correct graph parts, when is it still feasible to optimally match graphs? Smatch can be viewed as a spectrum from low to much admittance of small correct items which equals fast to slow matching:

- Smatch as we know it would be in the middle: optimal alignment is feasible in standard evaluation case, but not super fast

- Smatch on compressed graphs: optimal match is quite fast, but it has harsh scoring, very low tolerance to tiny correct things

- Smatch on reified or even edge2node transformed graphs: admits small partial credit for every smaller correct graph part. But optimal alignment may be extremely slow or infeasible to calculate

**Comment by flipz357** [comment]
Somewhat two many things going on by now in this issue by now, and none of them are really pressing. If somebody wants to implement a custom graph transform, there's also much info on that in the README.

So probably best closing this.
