### ISSUE TITLE
KeyError when processing a legal meaning representation graph

### ISSUE THREAD

**Issue by xiulinyang** [flipz357/smatchpp#5]
Hi, many thanks for providing this convenient tool to calculate SMATCH++! I had a problem when running the script. When comparing the following two graphs, I got an error below. Could you please offer some information on the solution? Thanks!

```
(s10196 / time.n.08
        :member-of (b10194 / box
                           :member (s10193 / "Oxford country"
                                           :Part s10195)
                           :member (s10195 / city.n.01
                                           :Name s10196)))

(b0 / "box"
	:member (s0 / "city.n.01"
		:Name "Bilbao"
		:Part-of (s3 / "country.n.02"
			:Name "Basque Country"))
	:member (s1 / "be.v.01"
		:Theme s0
		:Time (s2 / "time.n.08"
			:EQU "now"))
	:member s2
	:member s3)```

``File "MA_Thesis/SBN-evaluation-tool/2.evaluation-tool-detail/smatchpp/smatchpp/data_helpers.py", line 120, in _string2graph
    triple = (tmpsrc[nested_level], tmprel[nested_level], tgt) 
KeyError: 3``

**Comment by flipz357** [comment]
Hi @xiulinyang !

interesting, the error is due to the quotation marks around concepts (e.g. `b0 / "box"`) which sometimes happens in your AMRs. This is the first AMR that I have seen that does this.

What I mean is that if you change the AMRs from

```
(b0 / "box"
        :member (s0 / "city.n.01"
                :Name "Bilbao"
                :Part-of (s3 / "country.n.02"
                        :Name "Basque Country"))
        :member (s1 / "be.v.01"
                :Theme s0
                :Time (s2 / "time.n.08"
                        :EQU "now"))
        :member s2
        :member s3)
 
(s10196 / time.n.08
        :member-of (b10194 / box
                :member (s10193 / "Oxford Country"
                        :Part s10195)
        :member (s10195 / city.n.01
                :Name s10196)))
```

to 

```
(b0 / box
        :member (s0 / city.n.01
                :Name "Bilbao"
                :Part-of (s3 / country.n.02
                        :Name "Basque Country"))
        :member (s1 / be.v.01
                :Theme s0
                :Time (s2 / time.n.02
                        :EQU "now"))
        :member s2
        :member s3)

(s10196 / time.n.08
        :member-of (b10194 / box
                :member (s10193 / Oxford_country
                        :Part s10195)
        :member (s10195 / city.n.01
                :Name s10196)))
```

then it will work.

A question now is if I should change the code to accept your original AMRs. Can you tell me how you know that your AMRs are legal? I.e., do you have any source or example from the guidelines or annotated AMR corpora where concepts are enclosed in quotation marks like e.g., `(b0 / "box")`?

Best, Juri

**Comment by xiulinyang** [comment]
Hi Juri,

Thank you very much for your prompt reply! You are right - this is not an AMR but another meaning representation variant of Discourse Representation Structure. :)

I removed the quotation marks and connected those multiword expressions with underline and then it worked. Is there a better way to deal with concepts that have spaces between tokens? I don't want to change the original format a lot and there are some special cases such as time **3:00** which would give me an error if I remove the quotation marks. Also, the original SMATCH script works in the original format, so I want to make a fair comparison between these two metrics.  Many thanks in advance!

Best,

Xiulin

**Comment by xiulinyang** [comment]
Hi Juri,
Sorry, I missed your last paragraph. The standard to decide if my meaning representation is legal is just whether it can be converted to a penman notation. As far as I know, there is no strict requirement for quotation markers, but I tend to use quotations to mark the constant nodes (like names in AMR) because of the space issue. :)

**Comment by flipz357** [comment]
Yes, I think you are right, even though I haven't seen such AMR before, I think your approach to models multi-word concepts can be valid. Can you try out this [branch here](https://github.com/flipz357/smatchpp/tree/iss5) here? It should now work with multi-word separated concepts that are enclosed with quotation marks (e.g., `(b / "basque country")`). I'm traveling these days and need to run a few more tests before merging it into main, happy if you can give some feedback.

**Comment by xiulinyang** [comment]
Hi Juri,

Thank you! Sorry for getting back late. It went well so far! I will let you know if I come across further issues. Many thanks again!

**Comment by flipz357** [comment]
@xiulinyang : small update, the feature is now merged into main
