### ISSUE TITLE
Include point estimate (mean) of bootstrap

### ISSUE THREAD

**Issue by BramVanroy** [flipz357/smatchpp#6]
If I understand the output correctly, when we are bootstrapping we get results like this:

```
        "result": 81.3,
        "ci": [
            80.67,
            81.89
        ]
```

I think that the `result` is calculated independently, on the full corpus, and ci is the 95% CI min/max. It would be useful to also include the estimated mean based on the bootstrap. As far as I can tell, this is common in research papers too, where you report "85 +- 1.2" where 85 is the estimated mean and 1.2 the CI range with 95% confidence.

**Comment by flipz357** [comment]
Interesting, do you have a paper where the "85" really is the estimated mean and not just the sample statistic? I guess [this discussion](https://stats.stackexchange.com/questions/71357/why-not-report-the-mean-of-a-bootstrap-distribution) may be related, where the highest voted answers says

> ... The bootstrapped mean value is not a better estimator for your population parameter....

(than the sample statistic "result")

Technically, I think the bootstrap mean could be simply calculated from the `bootstrap_distribution` attribute of the scipy `res` object that you get from the [scipy bootstrap](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.bootstrap.html), so it should be easy to implement.

Maybe it can look like that:

```
"result": 81.3,
 "ci": [
          80.67,
          81.89
        ],
  "mean": x
```

but seeing this I think that it would maybe add more complexity in understanding/reporting the results than it may help?

**Comment by BramVanroy** [comment]
I agree that it might be confusing, and to be honest I am not 100% my request makes sense from a statistical perspective. I was creating the following graph.

![amr bar plot + CI](https://github.com/flipz357/smatchpp/assets/2779410/27e1db2f-a146-4e1d-b96c-ebdb21f45462)

These were created with the output of smatchpp, so "result" at the top and the the ci within brackets. In terms of notation, it would be easier to be able to write `mean +- 2*stdev`. But that is not _exactly_ the case, as an example:

- for the right most plot, the result is `73.4`. But the midpoint between 72.7 and 74.0 would be `73.5` (`73.5+-0.65`)

While these are very close, they are not exactly in the middle because the CI is calculated through bootstrapping and `result` is just the single calculation for the whole population, if I understand correctly. So in terms of notation we can't rightly report it as `73.5+-0.65` (because the this 73.5 is not the mean of the bootstrap but the independet calculation on the full poplation).

I am not sure whether it is clear what I am trying to say, sorry!

**Comment by flipz357** [comment]
I think it is clear what you want to say :-) You want to use the +- notation and then there are problems

1. boostrap mean != sample statistic, which would make +- weird

2. confidence intervals can also be asymetric, which would also make +- weird

While I think the standard deviation can also be easily obtained with scipy, the confidence interval is understood as more informative. So maybe it can help to slightly change a notation?

What I found nice is the notation that my colleague used in a [recent paper](https://aclanthology.org/2023.acl-short.79/) (I have seen others use it too). It looks like this:

![image](https://github.com/flipz357/smatchpp/assets/59831412/af2caef3-03a5-4bec-a6e4-0fe1ede48483)

The tiny left number is the lower confidence interval, the number in the middle the basic sample statistic, and the right tiny number the upper confidence interval.
